Aperol Spritz:
  collection: Classics
  ingredients:
    Aperol:
      amount: '1'
      units: oz
    Orange Liqueur:
      amount: '0.25'
      units: oz (optional)
    Prosecco:
      amount: '2'
      units: oz
  notes: The addition of orange liqueur is not traditional, but quite tasty.
Aviation:
  collection: Classics
  ingredients:
    Creme de Violette:
      amount: '0.25'
      units: oz
    Gin:
      amount: '2'
      units: oz
    Lemon Juice:
      amount: '0.75'
      units: oz
    Maraschino:
      amount: '0.5'
      units: oz
  notes: Shake until chilled. Garnish with a brandied cherry.
Bees Knees:
  collection: Classics
  ingredients:
    Gin:
      amount: '2'
      units: oz
    Honey Syrup:
      amount: '0.5'
      units: oz
    Lemon Juice:
      amount: '0.75'
      units: oz
  notes: Garnish with a lemon twist.
Boulevardier:
  collection: Classics
  ingredients:
    Campari:
      amount: '1'
      units: part
    Sweet Vermouth:
      amount: '1'
      units: part
    Whiskey:
      amount: '1'
      units: part
  notes: Stirred. Garnish with an orange twist.
Corn and Oil:
  collection: Classics
  ingredients:
    Falernum:
      amount: '0.5'
      units: oz
    Lime:
      amount: '1'
      units: squeeze
    Rum:
      amount: '2'
      units: oz
  notes: Ali's favorite. Stir this thing
Corpse Reviver No. 1:
  collection: Classics
  ingredients:
    Calvados:
      amount: '1'
      units: oz
    Cognac:
      amount: '1'
      units: oz
    Sweet Vermouth:
      amount: '0.5'
      units: oz
  notes: You probably are looking for the
Corpse Reviver No. 2:
  collection: Classics
  ingredients:
    Absinthe:
      amount: '2'
      units: dashes
    Cointreau:
      amount: '0.75'
      units: oz
    Gin:
      amount: '0.75'
      units: oz
    Lemon Juice:
      amount: '0.75'
      units: oz
    Lillet Blanc:
      amount: '0.75'
      units: oz
    Simple Syrup:
      amount: '0.5'
      units: tsp
  notes: Shake, strain, lemon twist to garnish.
Cosmopolitan:
  collection: Classics
  ingredients:
    Cointreau:
      amount: '1'
      units: oz
    Cranberry Juice:
      amount: '0.25'
      units: oz
    Lime Juice:
      amount: '0.5'
      units: oz
    Vodka (Inclusive):
      amount: '1.5'
      units: oz
  notes: Shaken, garnish with lime.
Daquiri:
  collection: Classics
  ingredients:
    Light Rum:
      amount: '2'
      units: oz
    Lime Juice:
      amount: '1'
      units: oz
    Simple Syrup:
      amount: '1'
      units: oz
  notes: Shake until chilled. Garnish with lime.
Dark and Stormy:
  collection: Classics
  ingredients:
    Dark Rum:
      amount: '2'
      units: oz
    Ginger Beer:
      amount: '5'
      units: oz
    Lime Juice:
      amount: '0.5'
      units: oz
  notes: Serve in a copper mug unless you're a baby about eating heavy metals I guess.
    Technically should be Goslings Black Seal rum, but eh
Death in the Afternoon:
  collection: Classics
  ingredients:
    Absinthe:
      amount: '1.5'
      units: oz
    Champagne:
      amount: '4.5'
      units: oz
  notes: Champagne flute.
Dublin Mule:
  collection: Classics
  ingredients:
    Ginger Beer:
      amount: '5'
      units: oz
    Lime Juice:
      amount: '0.5'
      units: oz
    Whiskey:
      amount: '2'
      units: oz
  notes: Serve in a copper mug unless you're a baby about eating heavy metals I guess.
French 75:
  collection: Classics
  ingredients:
    Champagne:
      amount: null
      units: to top
    Gin:
      amount: '2'
      units: oz
    Lemon Juice:
      amount: '0.5'
      units: oz
    Simple Syrup:
      amount: '2'
      units: dashes
  notes: Shaken, strained, and filled to the top with champagne. Garnish with a lemon
    twist.
Gimlet:
  collection: Classics
  ingredients:
    Gin:
      amount: '2'
      units: oz
    Lime Juice:
      amount: '0.75'
      units: oz
    Simple Syrup:
      amount: '0.75'
      units: oz
  notes: Shake and strain, baby.
Gin and Tonic:
  collection: Classics
  ingredients:
    Gin:
      amount: '2'
      units: oz
    Tonic:
      amount: '5'
      units: oz
  notes: I mean, duh.
Greyhound:
  collection: Classics
  ingredients:
    Gin:
      amount: '2'
      units: oz
    Grapefruit Juice:
      amount: '4'
      units: oz
  notes: Stirred. Garnish with lime.
Improved Whiskey Cocktail:
  collection: Classics
  ingredients:
    Absinthe:
      amount: '1'
      units: dash
    Angostura Bitters:
      amount: '1'
      units: dash
    Maraschino:
      amount: '1'
      units: bsp
    Peychauds Bitters:
      amount: '1'
      units: dash
    Simple Syrup:
      amount: '0.25'
      units: tsp
    Whiskey:
      amount: '2'
      units: oz
  notes: Lemon twist to garnish.
Last Word:
  collection: Classics
  ingredients:
    Gin:
      amount: '1'
      units: part
    Green Chartreuse:
      amount: '1'
      units: part
    Lime Juice:
      amount: '1'
      units: part
    Maraschino:
      amount: '1'
      units: part
  notes: Shake until chilled. Garnish with a maraschino cherry.
Littoral Coitus:
  collection: Classics
  ingredients:
    Cranberry Juice:
      amount: '2'
      units: oz
    Orange Juice:
      amount: '2'
      units: oz
    Peachtree:
      amount: '0.5'
      units: oz
    Vodka:
      amount: '1.5'
      units: oz
  notes: Garnish with an orange wedge.
Manhattan:
  collection: Classics
  ingredients:
    Angostura Bitters:
      amount: '2'
      units: dashes
    Rye Whiskey:
      amount: '2'
      units: oz
    Sweet Vermouth:
      amount: '1'
      units: oz
  notes: Stir in a mixing glass with ice, strain into a chilled martini glass.
Margarita:
  collection: Classics
  ingredients:
    Cointreau:
      amount: '1'
      units: oz
    Lime Juice:
      amount: '1'
      units: oz
    Tequila Blanco:
      amount: '2'
      units: oz
  notes: Shaken with ice. Salt the rim.
Martinez:
  collection: Classics
  ingredients:
    Angostura Bitters:
      amount: '2'
      units: dashes
    Gin:
      amount: '1.5'
      units: oz
    Maraschino:
      amount: '0.25'
      units: oz
    Sweet Vermouth:
      amount: '1.5'
      units: oz
  notes: Stirred. Should technically be Old Tom Gin.
Martini:
  collection: Classics
  ingredients:
    Dry Vermouth:
      amount: '0.5'
      units: oz
    Gin:
      amount: '3'
      units: oz
    Olive:
      amount: '1'
      units: piece
  notes: Olives are gross.
Mint Julep:
  collection: Classics
  ingredients:
    Bourbon:
      amount: '2'
      units: oz
    Mint:
      amount: '9'
      units: leaves
    Simple Syrup:
      amount: '0.25'
      units: oz
  notes: Muddle the leaves and simple. Add bourbon and fill with crushed ice. Garnish
    with a mint sprig.
Mojito:
  collection: Classics
  ingredients:
    Lime Juice:
      amount: '0.75'
      units: oz
    Mint:
      amount: '3'
      units: leaves
    Simple Syrup:
      amount: '0.5'
      units: oz
    White Rum:
      amount: '2'
      units: oz
  notes: I usually use Max's recipe wherein you muddle the leaves with sugar. But
    same basic process here, mix the simple and leaves together first, then rum, then
    fill.
Moscow Mule:
  collection: Classics
  ingredients:
    Ginger Beer:
      amount: '5'
      units: oz
    Lime Juice:
      amount: '0.5'
      units: oz
    Vodka:
      amount: '2'
      units: oz
  notes: Serve in a copper mug unless you're a baby about eating heavy metals I guess.
Negroni:
  collection: Classics
  ingredients:
    Campari:
      amount: '1'
      units: oz
    Gin:
      amount: '1'
      units: oz
    Sweet Vermouth:
      amount: '1'
      units: oz
  notes: Storred with ice in a mixing glass, and strained into a rocks glass over
    a large ice cube. Garnish with an orange twist.
Old Fashioned:
  collection: Classics
  ingredients:
    Angostura Bitters:
      amount: '2'
      units: dashes
    Sugar:
      amount: '1'
      units: tsp or cube
    Whisky:
      amount: '2'
      units: oz
  notes: Add sugar, bitters, and a tsp of water to a mixing glass and stir until sugar
    nearly dissolved. Add ice and bourbon, strain over one large ice cube. Garnish
    with an orange twist.
Paloma:
  collection: Classics
  ingredients:
    Grapefruit Soda:
      amount: null
      units: to top
    Lime Juice:
      amount: '0.5'
      units: oz
    Tequila:
      amount: '2'
      units: oz
  notes: Can have a salt rim.
Penicillin:
  collection: Classics
  ingredients:
    Honey Ginger Syrup:
      amount: '0.75'
      units: oz
    Islay Scotch:
      amount: '0.25'
      units: oz
    Lemon Juice:
      amount: '0.75'
      units: oz
    Scotch:
      amount: '2'
      units: oz
  notes: Shake until chilled. Islay is a float. Garnish with candied ginger.
Pina Colada:
  collection: Classics
  ingredients:
    Coconut Cream:
      amount: '1'
      units: oz
    Pineapple Juice:
      amount: '3'
      units: oz
    Rum:
      amount: '2.5'
      units: oz
  notes: I feel like this is supposed to have more stuff in it.
Ramos Gin Fizz:
  collection: Classics
  ingredients:
    Egg White:
      amount: '1'
      units: pcs
    Gin:
      amount: '2'
      units: oz
    Heavy Cream:
      amount: '1'
      units: oz
    Lemon:
      amount: '0.5'
      units: oz
    Lime:
      amount: '0.5'
      units: oz
    Orange Flower Water:
      amount: 2-3
      units: dashes
    Club Soda:
      amount: null
      units: to top
  notes: Shake everything except the foam.
Sazerac:
  collection: Classics
  ingredients:
    Absinthe:
      amount: '0.25'
      units: oz
    Peychauds Bitters:
      amount: '4'
      units: dashes
    Rye Whiskey:
      amount: '2.5'
      units: oz
    Sugar:
      amount: '1'
      units: cube
  notes: In a mixing glass, muddle the sugar cube, water, and Peychaud's Bitters,
    then add whiskey and stir. For the Absinthe, numerous delivery mechanisms are
    feasible. Doing a rinse of the glass and pouring it out is traditional, just adding
    it as an ingredient is reasonable, and using the atomizer is economical. Garnish
    with a lemon twist.
Screwdriver:
  collection: Classics
  ingredients:
    Orange Juice:
      amount: null
      units: to top
    Vodka:
      amount: '1.5'
      units: oz
  notes: Serve in Philip's Head
Sidecar:
  collection: Classics
  ingredients:
    Cognac:
      amount: '2'
      units: oz
    Cointreau:
      amount: '1'
      units: oz
    Lemon Juice:
      amount: '0.75'
      units: oz
  notes: Shake until chilled.
Tom Collins:
  collection: Classics
  ingredients:
    Gin:
      amount: '2'
      units: oz
    Lemon Juice:
      amount: '1'
      units: oz
    Simple Syrup:
      amount: '0.5'
      units: oz
    Club Soda:
      amount: null
      units: to top
  notes: Garnish with a lemon slice and a cherry. Should technically use Old Tom Gin
Trinidad Sour:
  collection: Classics
  ingredients:
    Coconut Cream:
      amount: '0.5'
      units: oz
    Lime:
      amount: '1'
      units: oz
    Reddit Aroma:
      amount: '1'
      units: oz
  notes: In the absence of coconut cream, simple is fine, or your favorite sweetener.
Vodka Gimlet:
  collection: Classics
  ingredients:
    Lime Juice:
      amount: '0.75'
      units: oz
    Simple Syrup:
      amount: '0.75'
      units: oz
    Vodka:
      amount: '2'
      units: oz
  notes: Shake and strain, baby.
Vodka Martini:
  collection: Classics
  ingredients:
    Dry Vermouth:
      amount: '0.5'
      units: oz
    Olive:
      amount: '1'
      units: piece
    Vodka:
      amount: '3'
      units: oz
  notes: Olives are gross.
Whiskey Sour:
  collection: Classics
  ingredients:
    Egg White:
      amount: '1'
      units: egg
    Lemon Juice:
      amount: '1'
      units: oz
    Sugar:
      amount: '1'
      units: tsp
    Whiskey:
      amount: '2'
      units: oz
  notes: Egg white tastes right. Add wet ingredients to the shaker, and "dry" shake
    for 30 seconds without ice. Then add ice, and shake until chilled. Strain into
    a rocks glass over fresh ice, and garnish with a few drops of angostura.
