Bourbon:
  collection: Tags
  ingredients:
  - four_roses_bourbon
  - high_west_bourye
  - yellowstone_bourbon
  notes: Should include all Bourbon Whiskeys
Canadian Whisky:
  collection: Tags
  ingredients:
  - black_velvet
  - 509_canadian_whisky
  notes: Should include all whisky from Canada
Irish Whiskey:
  collection: Tags
  ingredients:
  - kilbrin_irish
  - knappogue_12_year
  notes: Should include all whiskey from Ireland
Japanese Whisky:
  collection: Tags
  ingredients:
  notes: Should include all Japanese Whisky
Peated Whisky:
  collection: Tags
  ingredients:
  - islay_scotch
  - famous_grouse_smoky_black
  notes: Should include all peated whiskies/whiskeys, regardless of peat level
Rye Whiskey:
  collection: Tags
  ingredients:
  - bulleit_95_rye
  - high_west_bourye
  - sonoma_cherrywood_rye
  notes: Should include all Rye Whiskey (or Whisky)
Scotch Whisky:
  collection: Tags
  ingredients:
  - aultmore_12_year
  - famous_grouse
  - famous_grouse_smoky_black
  - the_deacon
  notes: Should include all Whisky from Scotland
Whiskey:
  collection: Tags
  ingredients:
  - Rye Whiskey
  - Whiskey (Specific)
  - Whisky (Specific)
  notes: All Whiskeys/Whiskies
Whiskey (Specific):
  collection: Tags
  ingredients:
  - Bourbon
  - Irish Whiskey
  notes: Whiskey spelled with the 'e'
Whisky:
  collection: Tags
  ingredients:
  - Whiskey
  notes: Alias of Whiskey
Whisky (Specific):
  collection: Tags
  ingredients:
  - Canadian Whisky
  - Japanese Whisky
  - Scotch Whisky
  notes: Whisky spelled without the 'e'
Whiskey (Inclusive):
  collection: Tags
  ingredients:
  - Whiskey
  - Whiskey (Specific)
  - cinnamon_infused_whiskey
  notes: Jack you might want to check this one, I did my best
Smoky Scotch Whisky:
  collection: Tags
  ingredients:
  - famous_grouse_smoky_black
  - islay_scotch
  notes: Anything that is a little smokier than usual
Smoky Scotch:
  collection: Tags
  ingredients:
  - Smoky Scotch Whisky
  - islay_scotch
  notes: Alias
Scotch:
  collection: Tags
  ingredients:
  - Scotch Whisky
  notes: Alias
