Flavored Vodka:
  collection: Tags
  ingredients:
  - red_huck_jar
  notes: ''
Vodka:
  collection: Tags
  ingredients:
  - placeholder_vodka
  notes: Plain vodka
Vodka (Inclusive):
  collection: Tags
  ingredients:
  - Flavored Vodka
  - Vodka
  notes: ''
